spring.application.name=rocketnotes

spring.datasource.url=jdbc:postgresql://postgres.railway.internal:5432/railway
spring.datasource.username=postgres
spring.datasource.password=kdVDmJlQkIdKZmaPyYVZikugqRTKTavx
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=8081
spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

authorization.jwt.secret=WriteHereYourSecretStringForTokenSigningCredentials
authorization.jwt.expiration.days=7

# Configuración de HTTPS
server.ssl.enabled=true
